/** 控制台展示的 API / 模型接入目录（营销与配置说明） */

export const API_INTEGRATIONS = [
  {
    id: "siliconflow",
    modelsZh: "Qwen3、Qwen2.5-VL、DeepSeek-V3",
    modelsEn: "Qwen3, Qwen2.5-VL, DeepSeek-V3",
    rolesZh: "意图 / 代码 / 视觉 / 安全",
    rolesEn: "Intent / Code / Vision / Safety",
    style: "OpenAI Compatible",
  },
  {
    id: "volcengine",
    modelsZh: "Doubao Lite / Pro",
    modelsEn: "Doubao Lite / Pro",
    rolesZh: "规划 / 兜底",
    rolesEn: "Planner / Fallback",
    style: "OpenAI Compatible",
  },
  {
    id: "openai",
    modelsZh: "GPT-4o / GPT-4.1 / o3",
    modelsEn: "GPT-4o / GPT-4.1 / o3",
    rolesZh: "通用 / 推理",
    rolesEn: "General / Reasoning",
    style: "OpenAI",
  },
  {
    id: "anthropic",
    modelsZh: "Claude 3.5 / 3.7 / 4",
    modelsEn: "Claude 3.5 / 3.7 / 4",
    rolesZh: "长文本 / 代码",
    rolesEn: "Long context / Code",
    style: "Anthropic",
  },
  {
    id: "deepseek",
    modelsZh: "DeepSeek-V3 / R1",
    modelsEn: "DeepSeek-V3 / R1",
    rolesZh: "推理 / 代码",
    rolesEn: "Reasoning / Code",
    style: "OpenAI Compatible",
  },
  {
    id: "moonshot",
    modelsZh: "Kimi k2 / moonshot-v1",
    modelsEn: "Kimi k2 / moonshot-v1",
    rolesZh: "长上下文对话",
    rolesEn: "Long-context chat",
    style: "OpenAI Compatible",
  },
  {
    id: "mimo",
    modelsZh: "MiMo 系列",
    modelsEn: "MiMo series",
    rolesZh: "对话 / 创作",
    rolesEn: "Chat / Creative",
    style: "OpenAI Compatible",
  },
  {
    id: "zhipu",
    modelsZh: "GLM-4 / GLM-4V",
    modelsEn: "GLM-4 / GLM-4V",
    rolesZh: "中文 / 多模态",
    rolesEn: "Chinese / Multimodal",
    style: "OpenAI Compatible",
  },
  {
    id: "dashscope",
    modelsZh: "Qwen-Max / Qwen-VL",
    modelsEn: "Qwen-Max / Qwen-VL",
    rolesZh: "通义系列",
    rolesEn: "Qwen series",
    style: "OpenAI Compatible",
  },
  {
    id: "minimax",
    modelsZh: "abab6 / MiniMax-M1",
    modelsEn: "abab6 / MiniMax-M1",
    rolesZh: "语音 / 对话",
    rolesEn: "Speech / Chat",
    style: "OpenAI Compatible",
  },
  {
    id: "groq",
    modelsZh: "Llama / Mixtral 高速推理",
    modelsEn: "Llama / Mixtral fast inference",
    rolesZh: "低延迟",
    rolesEn: "Low latency",
    style: "OpenAI Compatible",
  },
  {
    id: "together",
    modelsZh: "开源模型托管",
    modelsEn: "Open-source model hosting",
    rolesZh: "Llama / Qwen 等",
    rolesEn: "Llama / Qwen etc.",
    style: "OpenAI Compatible",
  },
] as const;
